#!/usr/bin/env python3
"""Render manuscript.json to an Overleaf-ready LaTeX project.

Reads the same JSON as ``build_docx.js``, so the Word and LaTeX submissions
cannot disagree with each other or with the analysis that produced the tables.

    python scripts/build_latex.py --json manuscript.json --figures figs --out overleaf

Writes ``main.tex``, ``references.bib``, ``figures/`` and a README, then zips the
sources for Overleaf's New Project -> Upload Project.
"""
from __future__ import annotations

import argparse
import json
import shutil
import zipfile
from pathlib import Path

# --------------------------------------------------------------------------- #
# escaping
# --------------------------------------------------------------------------- #

# Ordered: multi-character sequences first, so "10⁻⁴" is caught before "⁻".
_SEQ = [
    ("10⁻⁴", r"$10^{-4}$"),
    ("×10⁻⁴", r"\times 10^{-4}$"),
]
_CHAR = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "—": "---", "–": "--", "−": "$-$", "×": r"$\times$", "±": r"$\pm$",
    "≈": r"$\approx$", "≤": r"$\le$", "≥": r"$\ge$", "∈": r"$\in$",
    "·": r"$\cdot$", "“": "``", "”": "''", "‘": "`", "’": "'",
    "ö": r'\"o', "ä": r'\"a', "ü": r'\"u', "é": r"\'e", "è": r"\`e",
    "→": r"$\rightarrow$", "≠": r"$\neq$", "µ": r"$\mu$", "κ": r"$\kappa$",
    "α": r"$\alpha$", "÷": r"$\div$",
}


def esc(s: str) -> str:
    s = str(s)
    for a, b in _SEQ:
        s = s.replace(a, b)
    return "".join(_CHAR.get(c, c) for c in s)


PREAMBLE = r"""% !TeX program = pdflatex
%
% Generated by scripts/build_latex.py from manuscript.json.
% Prose may be edited here; the tables are regenerated from the analysis, so put
% numeric corrections in the analysis rather than in this file.
%
% Target journal: Journal of Imaging Informatics in Medicine (Springer).
%
\documentclass[11pt,a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{mathptmx}                 % Times text and math; on every TeX install
\usepackage[scaled=0.92]{helvet}
\usepackage[margin=1in]{geometry}
\usepackage{setspace}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{adjustbox}               % shrinks a table only when it is wider than the text
\usepackage{caption}
\usepackage[hidelinks]{hyperref}
\usepackage{lineno}
\usepackage{xcolor}

\captionsetup{font=small,labelfont=bf,justification=justified,singlelinecheck=false}
\renewcommand{\arraystretch}{1.12}
\setlength{\tabcolsep}{5pt}
\setcounter{secnumdepth}{2}

% Comment out for the camera-ready version.
\linenumbers
\doublespacing

\begin{document}
"""


def title_block(m: dict) -> str:
    out = [r"\begin{center}",
           r"{\Large\bfseries " + esc(m["title"]) + r"\par}", r"\vspace{1em}"]
    out.append(r"{\normalsize " +
               ", ".join(esc(a["name"]) + r"$^{" + ",".join(str(i) for i in a["aff"]) + "}$"
                         for a in m["authors"]) + r"\par}")
    out.append(r"\vspace{0.4em}")
    for i, aff in enumerate(m["affiliations"], 1):
        out.append(r"{\small\itshape " + f"{i} " + esc(aff) + r"\par}")
    corr = next(a for a in m["authors"] if a.get("corresponding"))
    out.append(r"{\small Corresponding author: " + esc(corr["name"]) +
               r" (\href{mailto:" + corr["email"] + "}{" + esc(corr["email"]) + r"})\par}")
    out.append(r"{\small\itshape Submitted to " + esc(m["journal"]) + r" as an Original Report.\par}")
    out.append(r"\end{center}")
    out.append(r"\vspace{0.6em}")
    return "\n".join(out)


def sections_tex(sections) -> list:
    L = []
    for sec in sections:
        L.append(r"\section{" + esc(sec["h"]) + "}")
        for t in sec.get("paras", []):
            L.append(esc(t)); L.append("")
        for sub in sec.get("subs", []):
            L.append(r"\subsection{" + esc(sub["h"]) + "}")
            for t in sub["paras"]:
                L.append(esc(t)); L.append("")
    return L


def body_tex(m: dict) -> str:
    L = [title_block(m), ""]
    L.append(r"\section*{Abstract}")
    L.append(r"\begin{spacing}{1.35}")
    for h, t in m["abstract_structured"]:
        L.append(r"\noindent\textbf{" + esc(h) + "} " + esc(t) + r"\par\smallskip")
    L.append(r"\end{spacing}")
    L.append(r"\vspace{0.5em}")
    L.append(r"\noindent\textbf{Keywords} " +
             r" $\cdot$ ".join(esc(k) for k in m["keywords"]))
    L.append(r"\clearpage")
    L.append("")
    L += sections_tex(m["sections"])
    L.append(r"\begin{spacing}{1.0}")
    for k, v in m["declarations"]:
        L.append(r"\subsection*{" + esc(k) + "}")
        L.append(esc(v) + r"\par\smallskip")
    L.append(r"\end{spacing}")
    L.append(r"\section*{References}")
    L.append(r"\begin{spacing}{1.0}")
    L.append(r"\begin{enumerate}\setlength{\itemsep}{2pt}")
    for r in m["references"]:
        L.append(r"\item " + esc(r))
    L.append(r"\end{enumerate}")
    L.append(r"\end{spacing}")
    L.append(r"\clearpage")
    return "\n".join(L)


def one_table(t: dict) -> list:
    L = []
    ncol = len(t["headers"])
    cap = r"\caption*{\textbf{" + esc(t["label"]) + ".} " + esc(t["caption"]) + "}"
    if t.get("structured"):
        first = 0.40 if ncol <= 4 else 0.28
        L.append(r"\small" if ncol <= 4 else r"\footnotesize")
        L.append(r"\begin{longtable}{@{}p{" + f"{first:.2f}" + r"\textwidth}" + "r" * (ncol - 1) + r"@{}}")
        L.append(cap + r"\\")
        L.append(r"\toprule")
        L.append(" & ".join(r"\textbf{" + esc(h) + "}" for h in t["headers"]) + r" \\")
        L.append(r"\midrule\endfirsthead")
        L.append(r"\toprule")
        L.append(" & ".join(r"\textbf{" + esc(h) + "}" for h in t["headers"]) + r" \\")
        L.append(r"\midrule\endhead")
        for row in t["rows"]:
            name = (r"\quad " if row["indent"] else r"\textbf{") + esc(row["cells"][0]) \
                   + ("" if row["indent"] else "}")
            rest = " & ".join(esc(c) for c in row["cells"][1:])
            L.append(f"{name} & {rest} " + r"\\")
        L.append(r"\bottomrule")
        L.append(r"\end{longtable}")
        L.append(r"\normalsize")
    else:
        L.append(r"\begin{table}[htbp]\centering" + (r"\footnotesize" if ncol >= 6 else r"\small"))
        L.append(cap)
        L.append(r"\begin{adjustbox}{max width=\textwidth}")
        L.append(r"\begin{tabular}{@{}l" + "c" * (ncol - 1) + r"@{}}")
        L.append(r"\toprule")
        L.append(" & ".join(r"\textbf{" + esc(h) + "}" for h in t["headers"]) + r" \\")
        L.append(r"\midrule")
        for row in t["rows"]:
            L.append(" & ".join(esc(c) for c in row) + r" \\")
        L.append(r"\bottomrule")
        L.append(r"\end{tabular}")
        L.append(r"\end{adjustbox}\end{table}")
    L.append("")
    return L


def tables_tex(tables: list, heading: str) -> str:
    L = [r"\section*{" + heading + "}", r"\begin{spacing}{1.0}"]
    for t in tables:
        L += one_table(t)
    L.append(r"\end{spacing}")
    L.append(r"\clearpage")
    return "\n".join(L)


def figures_tex(figures: list, heading: str) -> str:
    L = [r"\section*{" + heading + "}"]
    for f in figures:
        L.append(r"\begin{figure}[htbp]\centering")
        L.append(r"\includegraphics[width=0.95\textwidth]{figures/" + f["file"] + "}")
        L.append(r"\caption*{\textbf{" + esc(f["label"]) + ".} " + esc(f["caption"]) + "}")
        L.append(r"\end{figure}")
        L.append(r"\clearpage")
    return "\n".join(L)


def supplement_tex(m: dict) -> str:
    S = m["supplement"]
    L = [r"\begin{center}{\Large\bfseries " + esc(S["title"]) + r"\par}",
         r"{\normalsize " + esc(m["title"]) + r"\par}",
         r"{\small " + ", ".join(esc(a["name"]) for a in m["authors"]) + r"\par}",
         r"\end{center}", r"\vspace{1em}"]
    L += sections_tex(S["sections"])
    L.append(r"\clearpage")
    L.append(tables_tex(S["tables"], "Supplementary tables"))
    L.append(figures_tex(S["figures"], "Supplementary figures"))
    return "\n".join(L)


README = """# Overleaf project

Upload `overleaf-manuscript.zip` with **New Project -> Upload Project**. It
compiles with pdfLaTeX; nothing beyond a standard TeX Live installation is
needed.

```
main.tex            manuscript (structured abstract, main text, declarations,
                    references, main tables and figures)
supplement.tex      Data Supplement (supplementary methods and results,
                    Tables S1-S5, Figure S1)
figures/            600 dpi figures: Fig1, Fig2, FigS1
```

## Before you edit

**The tables are generated, not typed.** `scripts/manuscript_content.py` reads
the locked result files and writes `manuscript.json`; this project and the Word
version are both rendered from it. A numeric correction belongs in the analysis,
not in the `.tex`, and re-running the two build scripts regenerates everything.
Citations are numbered by first appearance when the JSON is emitted.

**Line numbers and double spacing are on**, which is what reviewers want.
Comment out `\\linenumbers` and change `\\doublespacing` for the camera-ready
version.

## Journal

Prepared for JCO Clinical Cancer Informatics (ASCO): Original Report, structured
abstract of at most 275 words, body of at most 3,000 words, at most six tables
and figures in the main text, single-blind review, Data Supplement allowed.
"""


def main(argv=None) -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--json", required=True)
    p.add_argument("--figures", required=True)
    p.add_argument("--out", required=True)
    a = p.parse_args(argv)

    m = json.loads(Path(a.json).read_text(encoding="utf-8"))
    out = Path(a.out)
    (out / "figures").mkdir(parents=True, exist_ok=True)
    for f in sorted(Path(a.figures).glob("Fig*.png")):
        shutil.copy(f, out / "figures" / f.name)

    main = (PREAMBLE + "\n" + body_tex(m) + "\n" + tables_tex(m["tables"], "Tables") + "\n"
            + figures_tex(m["figures"], "Figures") + "\n" + r"\end{document}" + "\n")
    (out / "main.tex").write_text(main, encoding="utf-8")
    supp = PREAMBLE + "\n" + supplement_tex(m) + "\n" + r"\end{document}" + "\n"
    (out / "supplement.tex").write_text(supp, encoding="utf-8")
    for stale in ("main_blinded.tex",):
        (out / stale).unlink(missing_ok=True)

    (out / "README.md").write_text(README, encoding="utf-8")

    zpath = out.parent / "overleaf-manuscript.zip"
    keep = {".tex", ".bib", ".md", ".png"}
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(out.rglob("*")):
            if f.is_file() and f.suffix in keep:
                z.write(f, f.relative_to(out))
    print(f"wrote {out}/main.tex, {out}/supplement.tex and {zpath}")


if __name__ == "__main__":
    main()
